name: Build application
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: app-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Install Node.js 24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # 7.0.0
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-deps-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
  build:
    name: Build Nuxt app
    needs: [install-dependencies]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Install Node.js 24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # 7.0.0
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-deps-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build